# -*- coding: utf-8 -*-
"""parsec_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yuyso6ulfjfLhSkJ6gB51qEba44AABj5
"""

!pip install tensorflow keras-hub scikit-learn seaborn matplotlib pillow opencv-python -q
!pip install --upgrade keras-hub -q

import os
import zipfile
import warnings
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import cv2
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, mixed_precision
import keras_hub
from sklearn.metrics import classification_report, confusion_matrix
from pathlib import Path

warnings.filterwarnings('ignore')
mixed_precision.set_global_policy('mixed_float16')

print("TensorFlow :", tf.__version__)
print("Keras Hub  :", keras_hub.__version__)

gpus = tf.config.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
print("GPUs:", gpus if gpus else "None — running on CPU")

zip_path     = '/content/drive/MyDrive/12-way script classification dataset-20260320T081258Z-3-001.zip'
extract_path = '/content/dataset'

os.makedirs(extract_path, exist_ok=True)
with zipfile.ZipFile(zip_path, 'r') as z:
    z.extractall(extract_path)

print("Extraction done")

train_dir = '/content/dataset/12-way script classification dataset/train_1800'
test_dir  = '/content/dataset/12-way script classification dataset/test_478'

print("Train classes:", sorted(os.listdir(train_dir)))
print("Test  classes:", sorted(os.listdir(test_dir)))

IMG_SIZE    = 224
BATCH_SIZE  = 32
NUM_CLASSES = 12
SEED        = 42
AUTOTUNE    = tf.data.AUTOTUNE

np.random.seed(SEED)
tf.random.set_seed(SEED)

def load_and_preprocess(path, label):
    img = tf.io.read_file(path)
    img = tf.image.decode_image(img, channels=3, expand_animations=False)
    img = tf.image.resize(img, [IMG_SIZE, IMG_SIZE])
    img = tf.cast(img, tf.float32) / 255.0
    return img, label

def build_dataset(data_dir, training=True):
    data_dir   = Path(data_dir)
    class_dirs = sorted([d for d in data_dir.iterdir() if d.is_dir()])
    cls_names  = [d.name for d in class_dirs]
    cls_to_idx = {n: i for i, n in enumerate(cls_names)}

    paths, labels = [], []
    for c in class_dirs:
        for img in c.glob('*'):
            if img.suffix.lower() in ['.jpg', '.png', '.jpeg']:
                paths.append(str(img))
                labels.append(cls_to_idx[c.name])

    paths  = np.array(paths)
    labels = np.array(labels)
    idx    = np.random.permutation(len(paths))
    paths, labels = paths[idx], labels[idx]

    if training:
        split       = int(0.9 * len(paths))
        tr_p, val_p = paths[:split],  paths[split:]
        tr_l, val_l = labels[:split], labels[split:]

        tr_l  = keras.utils.to_categorical(tr_l,  NUM_CLASSES)
        val_l = keras.utils.to_categorical(val_l, NUM_CLASSES)

        train_ds = (tf.data.Dataset.from_tensor_slices((tr_p, tr_l))
                    .shuffle(10000).map(load_and_preprocess)
                    .batch(BATCH_SIZE).prefetch(AUTOTUNE))
        val_ds   = (tf.data.Dataset.from_tensor_slices((val_p, val_l))
                    .map(load_and_preprocess)
                    .batch(BATCH_SIZE).prefetch(AUTOTUNE))
        return train_ds, val_ds, cls_names

    else:
        labels_oh = keras.utils.to_categorical(labels, NUM_CLASSES)
        test_ds   = (tf.data.Dataset.from_tensor_slices((paths, labels_oh))
                     .map(load_and_preprocess)
                     .batch(BATCH_SIZE).prefetch(AUTOTUNE))
        return test_ds, cls_names, labels, paths

train_ds, val_ds, class_names         = build_dataset(train_dir, training=True)
test_ds, _, true_labels, test_paths   = build_dataset(test_dir,  training=False)
print("Classes:", class_names)
print("Train batches:", len(train_ds), "| Val batches:", len(val_ds))

CANDIDATE_PRESETS = {
    'patch8' : 'vit_base_patch8_224_imagenet',
    'patch16': 'vit_base_patch16_224_imagenet',
    'patch32': 'vit_base_patch32_224_imagenet',
}

PATCH_PRESETS = {}
print("Checking available ViT presets...\n")
for pk, preset in CANDIDATE_PRESETS.items():
    try:
        _ = keras_hub.models.ViTBackbone.from_preset(preset)
        PATCH_PRESETS[pk] = preset
        print(f"  ✅ {pk:10s} → {preset}")
    except Exception as e:
        print(f"  ❌ {pk:10s} → NOT available ({e})")

print(f"\nWill train on: {list(PATCH_PRESETS.keys())}")

def build_model(pk, preset):
    backbone           = keras_hub.models.ViTBackbone.from_preset(preset)
    backbone.trainable = True

    inputs    = keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
    x         = backbone(inputs)       # (B, num_tokens+1, 768)
    cls_token = x[:, 0, :]            # CLS token

    x = layers.LayerNormalization()(cls_token)
    x = layers.Dense(768, activation='gelu')(x)
    x = layers.Dropout(0.3)(x)
    x = layers.Dense(384, activation='gelu')(x)
    x = layers.Dropout(0.2)(x)
    outputs = layers.Dense(NUM_CLASSES, activation='softmax', dtype='float32')(x)

    model = keras.Model(inputs, outputs, name=f'ViT_{pk}')
    model.compile(
        optimizer=keras.optimizers.Adam(5e-5),
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )
    n_tokens = (IMG_SIZE // int(pk.replace('patch', ''))) ** 2
    print(f"[{pk}] Tokens per image: {n_tokens}")
    return model

EPOCHS  = 8
results = {}
models  = {}

for pk, preset in PATCH_PRESETS.items():
    print(f"\n{'='*60}")
    print(f"  Training : {pk}  |  {preset}")
    print(f"{'='*60}")
    try:
        m = build_model(pk, preset)
        h = m.fit(train_ds, validation_data=val_ds, epochs=EPOCHS, verbose=1)

        test_loss, test_acc = m.evaluate(test_ds, verbose=0)
        print(f"\n  [{pk}] Test Accuracy: {test_acc:.4f}")

        y_pred = np.argmax(m.predict(test_ds, verbose=0), axis=1)

        results[pk] = {'history': h, 'test_acc': test_acc, 'y_pred': y_pred}
        models[pk]  = m

    except Exception as e:
        print(f"\n  ⚠️  Skipping {pk}: {e}")

print(f"\n✅ Trained models: {list(models.keys())}")

patch_keys = list(models.keys())
colors     = {'patch8': 'royalblue', 'patch16': 'darkorange', 'patch32': 'green'}

fig, axes = plt.subplots(1, 2, figsize=(16, 5))

for pk in patch_keys:
    h = results[pk]['history'].history
    c = colors.get(pk, 'gray')
    axes[0].plot(h['accuracy'],     label=f'{pk} train', color=c, linestyle='-')
    axes[0].plot(h['val_accuracy'], label=f'{pk} val',   color=c, linestyle='--')
    axes[1].plot(h['loss'],         label=f'{pk} train', color=c, linestyle='-')
    axes[1].plot(h['val_loss'],     label=f'{pk} val',   color=c, linestyle='--')

axes[0].set_title('Accuracy — Patch Size Comparison', fontsize=13)
axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Accuracy')
axes[0].legend(); axes[0].grid(True)

axes[1].set_title('Loss — Patch Size Comparison', fontsize=13)
axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Loss')
axes[1].legend(); axes[1].grid(True)

plt.tight_layout()
plt.savefig('training_curves_comparison.png', dpi=150)
plt.show()

n_models = len(patch_keys)
fig, axes = plt.subplots(1, n_models, figsize=(13 * n_models, 11))

if n_models == 1:
    axes = [axes]

for ax, pk in zip(axes, patch_keys):
    cm_mat = confusion_matrix(true_labels, results[pk]['y_pred'])
    sns.heatmap(cm_mat, annot=True, fmt='d', ax=ax,
                xticklabels=class_names, yticklabels=class_names,
                cmap='Blues')
    ax.set_title(f'{pk}  |  Test Acc: {results[pk]["test_acc"]:.4f}', fontsize=14)
    ax.set_xlabel('Predicted'); ax.set_ylabel('True')
    ax.tick_params(axis='x', rotation=45)

plt.suptitle('Confusion Matrix Comparison — Patch Size Experiment',
             fontsize=16, y=1.01)
plt.tight_layout()
plt.savefig('confusion_matrices_all_patches.png', dpi=150, bbox_inches='tight')
plt.show()

def gradcam_heatmap(model, img_array, class_idx=None):
    """
    Grad-CAM over ViT backbone patch tokens.
    img_array : numpy (224, 224, 3) float32 in [0,1]
    Returns   : heatmap (H_patches, W_patches), predicted class index
    """
    img_tensor = tf.convert_to_tensor(img_array[np.newaxis], dtype=tf.float32)
    backbone   = model.layers[1]

    grad_model = keras.Model(
        inputs  = model.inputs,
        outputs = [backbone.output, model.output]
    )

    with tf.GradientTape() as tape:
        backbone_out, preds = grad_model(img_tensor, training=False)
        if class_idx is None:
            class_idx = int(tf.argmax(preds[0]).numpy())
        score = preds[:, class_idx]

    grads       = tape.gradient(score, backbone_out)   # (1, T+1, 768)
    patch_grads = grads[0, 1:, :]                      # remove CLS  (T, 768)

    weights  = tf.reduce_mean(patch_grads, axis=-1)    # (T,)
    weights  = tf.nn.relu(weights).numpy()

    num_patches = int(np.sqrt(len(weights)))
    heatmap     = weights[:num_patches * num_patches].reshape(num_patches, num_patches)
    heatmap     = (heatmap - heatmap.min()) / (heatmap.max() + 1e-8)

    return heatmap, class_idx


def overlay_heatmap(img_array, heatmap, alpha=0.45):
    """Resize heatmap to image size and blend with original."""
    h, w            = img_array.shape[:2]
    heatmap_resized = cv2.resize(heatmap, (w, h))
    heatmap_uint8   = np.uint8(255 * heatmap_resized)
    heatmap_color   = cv2.applyColorMap(heatmap_uint8, cv2.COLORMAP_JET)
    heatmap_color   = cv2.cvtColor(heatmap_color, cv2.COLOR_BGR2RGB)
    img_uint8       = np.uint8(255 * img_array)
    superimposed    = cv2.addWeighted(img_uint8, 1 - alpha, heatmap_color, alpha, 0)
    return superimposed

def load_img_numpy(path):
    img = tf.io.read_file(path)
    img = tf.image.decode_image(img, channels=3, expand_animations=False)
    img = tf.image.resize(img, [IMG_SIZE, IMG_SIZE])
    img = tf.cast(img, tf.float32) / 255.0
    return img.numpy()

# One sample per class
samples_per_class = {}
for path, label in zip(test_paths, true_labels):
    if label not in samples_per_class:
        samples_per_class[label] = path
    if len(samples_per_class) == NUM_CLASSES:
        break

n_cols = len(patch_keys) + 1   # original + one col per model
fig, axes = plt.subplots(NUM_CLASSES, n_cols,
                         figsize=(5 * n_cols, 4 * NUM_CLASSES))

# Ensure axes is always 2D
if NUM_CLASSES == 1:
    axes = np.expand_dims(axes, 0)
if n_cols == 1:
    axes = np.expand_dims(axes, 1)

for row, cls_idx in enumerate(sorted(samples_per_class.keys())):
    img_np = load_img_numpy(samples_per_class[cls_idx])

    # Col 0 — original image
    axes[row, 0].imshow(img_np)
    axes[row, 0].set_title(f'Original\n{class_names[cls_idx]}', fontsize=9)
    axes[row, 0].axis('off')

    # Remaining cols — one per patch model
    for col, pk in enumerate(patch_keys):
        try:
            heatmap, pred_cls = gradcam_heatmap(models[pk], img_np, class_idx=cls_idx)
            overlay           = overlay_heatmap(img_np, heatmap)
            num_patches       = int(np.sqrt(heatmap.size))
            axes[row, col+1].imshow(overlay)
            axes[row, col+1].set_title(
                f'{pk} ({num_patches}×{num_patches} grid)\nPred: {class_names[pred_cls]}',
                fontsize=9)
        except Exception as e:
            axes[row, col+1].text(0.5, 0.5, f'Error:\n{str(e)[:50]}',
                                  ha='center', va='center', fontsize=7,
                                  transform=axes[row, col+1].transAxes)
        axes[row, col+1].axis('off')

plt.suptitle(f'Grad-CAM Attention Heatmaps | Models: {patch_keys}\n'
             f'Each row = one script class', fontsize=14, y=1.005)
plt.tight_layout()
plt.savefig('attention_heatmaps_all_classes.png', dpi=130, bbox_inches='tight')
plt.show()
print("Saved: attention_heatmaps_all_classes.png")

print("\n" + "="*62)
print(f"{'Patch':10s} {'Tokens':10s} {'Test Acc':15s} {'vs patch16'}")
print("="*62)

baseline = results.get('patch16', {}).get('test_acc', None)

for pk in patch_keys:
    n_tokens = (IMG_SIZE // int(pk.replace('patch', ''))) ** 2
    acc      = results[pk]['test_acc']
    if baseline:
        diff     = acc - baseline
        diff_str = f"+{diff:.4f}" if diff >= 0 else f"{diff:.4f}"
        note     = " ← baseline" if pk == 'patch16' else ""
    else:
        diff_str = "N/A"
        note     = ""
    print(f"{pk:10s} {n_tokens:<10d} {acc:<15.4f} {diff_str}{note}")

print("="*62)

# Full classification report for best model
best_pk = max(results, key=lambda k: results[k]['test_acc'])
print(f"\n✅ Best model: {best_pk}  (Acc: {results[best_pk]['test_acc']:.4f})\n")
print(classification_report(true_labels, results[best_pk]['y_pred'],
                             target_names=class_names))

