# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t4jx8qlUQ0PSn3z9QSQhtrXZFNn6-ylX
"""

!pip install tensorflow keras-hub scikit-learn seaborn matplotlib pillow -q

import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import keras_hub
from sklearn.metrics import classification_report, confusion_matrix
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

print("TensorFlow:", tf.__version__)
print("Keras Hub :", keras_hub.__version__)

gpus = tf.config.list_physical_devices('GPU')
if gpus:
    for gpu in gpus:
        tf.config.experimental.set_memory_growth(gpu, True)

from tensorflow.keras import mixed_precision
mixed_precision.set_global_policy('mixed_float16')

import zipfile
import os

zip_path     = '/content/drive/MyDrive/12-way script classification dataset-20260320T081258Z-3-001.zip'
extract_path = '/content/dataset'

os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Extraction done")
print(os.listdir(extract_path))

import os

extract_path = '/content/dataset'

for root, dirs, files in os.walk(extract_path):
    level = root.replace(extract_path, '').count(os.sep)
    if level < 3:
        print(' ' * 2 * level + os.path.basename(root) + '/')

train_dir = '/content/dataset/12-way script classification dataset/train_1800'
test_dir  = '/content/dataset/12-way script classification dataset/test_478'

print("Train classes:", sorted(os.listdir(train_dir)))
print("Test classes :", sorted(os.listdir(test_dir)))

IMG_SIZE = 224
BATCH_SIZE = 32
NUM_CLASSES = 12
SEED = 42

np.random.seed(SEED)
tf.random.set_seed(SEED)

AUTOTUNE = tf.data.AUTOTUNE

def load_and_preprocess(path, label):
    img = tf.io.read_file(path)
    img = tf.image.decode_image(img, channels=3, expand_animations=False)
    img = tf.image.resize(img, [IMG_SIZE, IMG_SIZE])
    img = tf.cast(img, tf.float32) / 255.0
    return img, label

def build_dataset(data_dir, training=True):
    data_dir = Path(data_dir)
    class_dirs = sorted([d for d in data_dir.iterdir() if d.is_dir()])
    cls_names = [d.name for d in class_dirs]
    cls_to_idx = {name: idx for idx, name in enumerate(cls_names)}

    paths, labels = [], []

    for c in class_dirs:
        for img in c.glob('*'):
            if img.suffix.lower() in ['.jpg', '.png', '.jpeg']:
                paths.append(str(img))
                labels.append(cls_to_idx[c.name])

    paths = np.array(paths)
    labels = np.array(labels)

    idx = np.random.permutation(len(paths))
    paths, labels = paths[idx], labels[idx]

    if training:
        split = int(0.9 * len(paths))
        tr_p, val_p = paths[:split], paths[split:]
        tr_l, val_l = labels[:split], labels[split:]

        tr_l = tf.keras.utils.to_categorical(tr_l, NUM_CLASSES)
        val_l = tf.keras.utils.to_categorical(val_l, NUM_CLASSES)

        train_ds = tf.data.Dataset.from_tensor_slices((tr_p, tr_l))
        train_ds = train_ds.shuffle(10000).map(load_and_preprocess).batch(BATCH_SIZE).prefetch(AUTOTUNE)

        val_ds = tf.data.Dataset.from_tensor_slices((val_p, val_l))
        val_ds = val_ds.map(load_and_preprocess).batch(BATCH_SIZE).prefetch(AUTOTUNE)

        return train_ds, val_ds, cls_names

    else:
        labels_oh = tf.keras.utils.to_categorical(labels, NUM_CLASSES)

        test_ds = tf.data.Dataset.from_tensor_slices((paths, labels_oh))
        test_ds = test_ds.map(load_and_preprocess).batch(BATCH_SIZE).prefetch(AUTOTUNE)

        return test_ds, cls_names, labels

train_ds, val_ds, class_names = build_dataset(train_dir, True)
test_ds, _, true_labels = build_dataset(test_dir, False)

def get_parseq_encoder():

    backbone = keras_hub.models.ViTBackbone.from_preset(
        "vit_base_patch16_224_imagenet"   # fixed
    )

    backbone.trainable = True
    return backbone

def build_parseq_style_model():

    backbone = get_parseq_encoder()

    inputs = keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
    x = backbone(inputs)

    cls_token = x[:, 0, :]

    # stronger head (important change)
    x = layers.LayerNormalization()(cls_token)
    x = layers.Dense(768, activation='gelu')(x)
    x = layers.Dropout(0.3)(x)
    x = layers.Dense(384, activation='gelu')(x)
    x = layers.Dropout(0.2)(x)

    outputs = layers.Dense(NUM_CLASSES, activation='softmax', dtype='float32')(x)

    model = keras.Model(inputs, outputs)

    model.compile(
        optimizer=keras.optimizers.Adam(5e-5),
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )

    return model

model = build_parseq_style_model()

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=8
)

test_loss, test_acc = model.evaluate(test_ds)
print("Test Accuracy:", test_acc)

y_pred = np.argmax(model.predict(test_ds), axis=1)
y_true = true_labels

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(12,10))
sns.heatmap(cm, annot=True, fmt='d', xticklabels=class_names, yticklabels=class_names)
plt.title("Confusion Matrix - PARSeq Style ViT")
plt.show()

